
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePttSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ptt_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAdaptiveVocabularyEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_adaptive_vocabulary_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAdaptiveVoiceProfileEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_adaptive_voice_profile_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessAction(key: number, name: string, prompt: string, model: string | null, providerId: string | null) : Promise<Result<PostProcessAction, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_action", { key, name, prompt, model, providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessAction(key: number, name: string, prompt: string, model: string | null, providerId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_action", { key, name, prompt, model, providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessAction(key: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_action", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addSavedProcessingModel(providerId: string, modelId: string, label: string) : Promise<Result<SavedProcessingModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_saved_processing_model", { providerId, modelId, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSavedProcessingModel(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_saved_processing_model", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister a binding while the user is editing it in the UI.
 * This avoids firing the action while keys are being recorded.
 */
async suspendBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register the binding after the user has finished editing.
 */
async resumeBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWakeWordEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_wake_word_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start key recording mode
 */
async startNativeKeyboardRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_native_keyboard_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopNativeKeyboardRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_native_keyboard_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async togglePause() : Promise<boolean> {
    return await TAURI_INVOKE("toggle_pause");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStartupWarmupStatus() : Promise<Result<StartupWarmupStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_startup_warmup_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSettings(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_settings", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importSettings(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_settings", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetAllSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_all_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMachineDeviceId() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_machine_device_id") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIntegritySnapshot() : Promise<IntegritySnapshot> {
    return await TAURI_INVOKE("get_integrity_snapshot");
},
async getLicenseRuntimeState() : Promise<Result<LicenseRuntimeState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_license_runtime_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSecureAuthToken() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_secure_auth_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async storeSecureAuthToken(token: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("store_secure_auth_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRuntimeDiagnostics() : Promise<Result<RuntimeDiagnostics, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_runtime_diagnostics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportRuntimeDiagnostics(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_runtime_diagnostics", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSupportPackage(path: string, supportReport: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_support_package", { path, supportReport }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async submitVoiceFeedbackCommand(input: VoiceFeedbackInput) : Promise<Result<VoiceFeedbackEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_voice_feedback_command", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listVoiceFeedbackCommand(limit: number | null) : Promise<Result<VoiceFeedbackEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_voice_feedback_command", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async summarizeVoiceFeedbackCommand(limit: number | null) : Promise<Result<VoiceFeedbackSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_voice_feedback_command", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentAppContext() : Promise<Result<AppTranscriptionContext, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_app_context") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAdaptiveRuntimeProfile() : Promise<Result<AdaptiveMachineProfile | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_adaptive_runtime_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsOrDownloads() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_or_downloads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerTranscriptionBinding(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_transcription_binding", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleTranscriptionBinding(bindingId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_transcription_binding", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries() : Promise<Result<HistoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntriesPaginated(limit: number, offset: number) : Promise<Result<[HistoryEntry[], boolean], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries_paginated", { limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reprocessHistoryEntry(id: number, modelId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reprocess_history_entry", { id, modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyHistoryPostProcessAction(id: number, actionKey: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_history_post_process_action", { id, actionKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearHistoryPostProcessAction(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history_post_process_action", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryStats() : Promise<Result<HistoryStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportHistoryEntries(format: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_history_entries", { format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcribeAudioFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcribeAudioFileDetailed(path: string) : Promise<Result<AudioTranscriptionDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio_file_detailed", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update only the transcription text of a history entry (user manual edit).
 * Also feeds the correction into the adaptive VocabularyStore so future
 * transcriptions of the same words benefit immediately.
 */
async updateHistoryEntryText(id: number, newText: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_entry_text", { id, newText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAllHistory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNotes() : Promise<Result<NoteEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_notes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createNote(title: string, content: string) : Promise<Result<NoteEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { title, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateNote(id: number) : Promise<Result<NoteEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateNote(id: number, title: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_note", { id, title, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNotePinned(id: number, pinned: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_note_pinned", { id, pinned }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNoteArchived(id: number, archived: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_note_archived", { id, archived }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNoteCategory(id: number, category: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_note_category", { id, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNote(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchNotes(query: string) : Promise<Result<NoteEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_notes", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportNote(id: number, format: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_note", { id, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async summarizeNote(id: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async extractNoteActions(id: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_note_actions", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateNoteTitle(id: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_note_title", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeNote() : Promise<void> {
    await TAURI_INVOKE("close_note");
},
async setActiveNote(id: number | null) : Promise<void> {
    await TAURI_INVOKE("set_active_note", { id });
},
async getMeetings() : Promise<Result<MeetingEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meetings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createMeeting(title: string, appName: string) : Promise<Result<MeetingEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_meeting", { title, appName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateMeeting(id: number) : Promise<Result<MeetingEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMeeting(id: number, title: string, transcript: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_meeting", { id, title, transcript }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMeetingPinned(id: number, pinned: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_meeting_pinned", { id, pinned }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMeetingArchived(id: number, archived: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_meeting_archived", { id, archived }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMeetingCategory(id: number, category: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_meeting_category", { id, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMeeting(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchMeetings(query: string) : Promise<Result<MeetingEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_meetings", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportMeeting(id: number, format: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_meeting", { id, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async summarizeMeeting(id: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async extractMeetingActions(id: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_meeting_actions", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateMeetingTitle(id: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_meeting_title", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateMeetingChapterTitles(id: number) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_meeting_chapter_titles", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the name of the currently running meeting app, or `null` if none detected.
 */
async detectActiveMeetingApp() : Promise<string | null> {
    return await TAURI_INVOKE("detect_active_meeting_app");
},
/**
 * Close the active meeting so the next `meeting_key` press starts a fresh one.
 */
async closeMeeting() : Promise<void> {
    await TAURI_INVOKE("close_meeting");
},
async setActiveMeeting(id: number | null) : Promise<void> {
    await TAURI_INVOKE("set_active_meeting", { id });
},
/**
 * Import a WAV audio file and create a meeting with speaker diarization.
 * Downloads the Sortformer model on first use (~50 MB).
 */
async transcribeAudioToMeeting(path: string) : Promise<Result<MeetingEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio_to_meeting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDictionary() : Promise<Result<DictionaryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dictionary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addDictionaryEntry(from: string, to: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_dictionary_entry", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeDictionaryEntry(from: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_dictionary_entry", { from }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDictionaryEntry(from: string, to: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dictionary_entry", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearDictionary() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_dictionary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportDictionary() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_dictionary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importDictionary(json: string, replace: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_dictionary", { json, replace }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncWorkspaceCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_workspace_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Analyse the difference between an original transcription and a user correction.
 * Returns word-level substitution candidates enriched with dictionary state and counts.
 * Does NOT record the correction — call `record_correction` separately.
 */
async analyzeCorrection(original: string, corrected: string) : Promise<Result<CorrectionSuggestion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_correction", { original, corrected }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a correction and optionally add it to the dictionary.
 * 
 * - If `add_to_dict` is true, the entry is added immediately.
 * - If the running count reaches `AUTO_ADD_THRESHOLD`, the entry is added automatically.
 * 
 * When the `to` value is a single proper-noun word, it is also added to
 * `custom_words` so the transcription model is aware of it in future sessions.
 * 
 * Returns the new count for this correction pair.
 */
async recordCorrection(from: string, to: string, addToDict: boolean) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_correction", { from, to, addToDict }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return aggregated learning stats for the current user.
 */
async getLearningStats() : Promise<Result<LearningStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_learning_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the current user profile (learned terms + metadata).
 */
async getUserProfile() : Promise<Result<UserProfile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_user_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan every dictionary `to` value and promote single-word proper-looking
 * terms into `custom_words` so the model is aware of them during transcription.
 * 
 * Safe to call multiple times — duplicates are skipped.
 * Returns the number of new terms added.
 */
async syncDictionaryToProfile() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_dictionary_to_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a term from the user's learned profile (custom_words).
 */
async removeProfileTerm(term: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_profile_term", { term }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWeeklyReport() : Promise<Result<WeeklyReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_weekly_report") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVoiceSnippets() : Promise<VoiceSnippet[]> {
    return await TAURI_INVOKE("get_voice_snippets");
},
async addVoiceSnippet(trigger: string, expansion: string) : Promise<Result<VoiceSnippet, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_voice_snippet", { trigger, expansion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeVoiceSnippet(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_voice_snippet", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateVoiceSnippet(id: string, trigger: string, expansion: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_voice_snippet", { id, trigger, expansion }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncWorkspaceVoiceSnippets(snippets: VoiceSnippet[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_workspace_voice_snippets", { snippets }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the list of apps detected during the last N dictation sessions.
 */
async getRecentApps() : Promise<RecentAppEntry[]> {
    return await TAURI_INVOKE("get_recent_apps");
},
/**
 * Return all user-defined app-category overrides.
 */
async listAppContextOverrides() : Promise<AppContextOverride[]> {
    return await TAURI_INVOKE("list_app_context_overrides");
},
/**
 * Force a specific category for a given process name.
 * `process_name` is the `.exe` filename (e.g. `"notion.exe"`).
 */
async setAppContextOverride(processName: string, category: AppContextCategory) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_app_context_override", { processName, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a previously set category override for a process.
 */
async removeAppContextOverride(processName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_app_context_override", { processName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable or disable the automatic app-context feature globally.
 */
async setAppContextEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_app_context_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSecureAuthToken() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_secure_auth_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSecureAuthToken(token: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_secure_auth_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearSecureAuthToken() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_secure_auth_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSecureAuthSession() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_secure_auth_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSecureAuthSession(sessionJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_secure_auth_session", { sessionJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearSecureAuthSession() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_secure_auth_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSecureLicenseBundle() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_secure_license_bundle") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSecureLicenseBundle(bundleJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_secure_license_bundle", { bundleJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearSecureLicenseBundle() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_secure_license_bundle") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stub implementation for non-macOS platforms
 * Always returns false since laptop detection is macOS-specific
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Called by the frontend just before opening the browser for OAuth login.
 * Records that a login flow is in progress and returns the one-time `state`
 * that must come back on the deep-link callback. Without this, any app or URL
 * can hijack the session via a crafted `vocalype://auth-callback?token=...`
 * link (deep-link CSRF).
 */
async startBrowserAuth() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_browser_auth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkOllamaStatus() : Promise<Result<OllamaStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_ollama_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn `ollama serve` detached. Searches common install paths on Windows
 * in case ollama is not in PATH.
 */
async startOllamaServe() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_ollama_serve") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pull an Ollama model, emitting `ollama-pull-progress` events so the
 * frontend can show a live progress bar.
 * Emits `ollama-pull-done` when complete or `ollama-pull-error` on failure.
 */
async pullOllamaModel(model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pull_ollama_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pre-load a model into Ollama's memory so the first real request is instant.
 * Sends a tiny dummy chat completion with `keep_alive: -1` so the model
 * stays loaded indefinitely after warmup.
 * Fire-and-forget from the frontend — errors are silently ignored.
 */
async warmupOllamaModel(model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("warmup_ollama_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full setup: download binary + model (if needed) then start the server.
 * Emits `llm-setup-progress` events so the frontend can show a progress bar.
 * Idempotent — safe to call on every "Activer" click.
 */
async setupLlamaServer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("setup_llama_server") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lightweight status check — no side effects.
 */
async checkLlamaServerStatus() : Promise<Result<LlamaServerStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_llama_server_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the server (called when "Clean for LLM" is disabled or app exits).
 */
async stopLlamaServer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_llama_server") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AdaptiveMachineProfile = { profile_schema_version?: number; app_version?: string; backend_version?: string; machine_score_details?: MachineScoreDetails; machine_tier: MachineTier; cpu_brand: string; logical_cores: number; total_memory_gb: number; low_power_cpu: boolean; gpu_detected?: boolean; gpu_kind?: GpuKind; gpu_name?: string | null; npu_detected?: boolean; npu_kind?: NpuKind; npu_name?: string | null; copilot_plus_detected?: boolean; on_battery?: boolean | null; power_mode?: PowerMode; thermal_degraded?: boolean; runtime_power_snapshot_at?: number | null; recommended_model_id: string; secondary_model_id: string | null; active_runtime_model_id?: string | null }
export type AppContextCategory = 
/**
 * Code editors, IDEs, terminals
 */
"code" | 
/**
 * Email clients and webmail
 */
"email" | 
/**
 * Chat / messaging apps
 */
"chat" | 
/**
 * Traditional document editors (Word, LibreOffice)
 */
"document" | 
/**
 * Notes and PKM apps (Notion, Obsidian, Logseq…)
 */
"notes" | 
/**
 * Web browsers (category refined further via window title)
 */
"browser" | 
/**
 * App not recognised — neutral behaviour
 */
"unknown"
/**
 * User-defined category override for a specific process.
 */
export type AppContextOverride = { 
/**
 * Same key format as `AppTranscriptionContext::process_name`.
 */
process_name: string; category: AppContextCategory }
export type AppSettings = { 
/**
 * Schema version used to drive forward migrations.
 * Never set this manually — it is managed by `migrate_settings`.
 */
settings_version?: number; bindings: Partial<{ [key in string]: ShortcutBinding }>; push_to_talk: boolean; audio_feedback: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; selected_model?: string; always_on_microphone?: boolean; 
/**
 * When true, Vocalype listens for the wake word "dictate" in the
 * background and starts a hands-free recording session automatically.
 * Requires the microphone stream to be open (AlwaysOn mode recommended).
 */
wake_word_enabled?: boolean; 
/**
 * Sliding window of the last observed inter-word pause durations (ms).
 * Accumulated across all recording modes to calibrate the adaptive
 * silence threshold for wake-word auto-stop.
 */
speaking_rate_pauses?: number[]; 
/**
 * Canonical recording mode — supersedes the `push_to_talk` and
 * `always_on_microphone` boolean pair. Populated from those booleans
 * on first load via settings migration (T11). New code should read this
 * field; old code continues to use the booleans until migration is done.
 */
recording_mode?: RecordingMode; selected_microphone?: string | null; selected_microphone_index?: string | null; clamshell_microphone?: string | null; clamshell_microphone_index?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition; debug_mode?: boolean; log_level?: LogLevel; custom_words?: string[]; workspace_custom_words?: string[]; adaptive_vocabulary_enabled?: boolean; adaptive_voice_profile_enabled?: boolean; model_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; recording_retention_period?: RecordingRetentionPeriod; 
/**
 * When false, audio is never written to disk — only the transcription text is saved.
 * Saves significant disk space (WAV at 16 kHz 16-bit ≈ 32 KB/s).
 */
save_audio_recordings?: boolean; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; 
/**
 * When true, LLM post-processing fires automatically whenever the
 * session glossary signals a code context (≥ 3 extracted identifiers).
 */
llm_auto_mode?: boolean; post_process_provider_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: Partial<{ [key in string]: string }>; post_process_models?: Partial<{ [key in string]: string }>; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; mute_while_recording?: boolean; append_trailing_space?: boolean; app_language?: string; experimental_enabled?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; paste_delay_ms?: number; typing_tool?: TypingTool; external_script_path: string | null; post_process_actions?: PostProcessAction[]; saved_processing_models?: SavedProcessingModel[]; adaptive_profile_applied?: boolean; adaptive_machine_profile?: AdaptiveMachineProfile | null; 
/**
 * Whether the automatic app-context feature is enabled globally.
 */
app_context_enabled?: boolean; 
/**
 * Boost microphone gain for whisper / low-volume recording.
 */
whisper_mode?: boolean; 
/**
 * Voice snippets: short trigger phrases → long expansions.
 */
voice_snippets?: VoiceSnippet[]; 
/**
 * Automatically learn word corrections from clipboard changes after paste.
 */
auto_learn_dictionary?: boolean; 
/**
 * Automatically pause media players (Spotify, etc.) during recording.
 */
auto_pause_media?: boolean; 
/**
 * When true, dictation in code editors is sent to a local LLM (Ollama)
 * and the result is pasted as formatted code instead of raw text.
 */
voice_to_code_enabled?: boolean; 
/**
 * Model name to use for Voice-to-Code (e.g. "devstral", "ministral-3:8b").
 * Applies to the "ollama" provider.
 */
voice_to_code_model?: string; 
/**
 * Set to true after the Voice-to-Code discovery prompt has been shown
 * once, so it never appears again.
 */
voice_to_code_onboarding_done?: boolean }
export type AppTranscriptionContext = { 
/**
 * Stable process identifier: `.exe` filename on Windows (e.g. `"code.exe"`).
 */
process_name: string | null; 
/**
 * Window title at capture time.
 */
window_title: string | null; category: AppContextCategory; 
/**
 * Detected coding language (only set when category == Code).
 */
code_language?: CodeLanguage | null; detected_at_ms: number }
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AudioInputLevelState = "unknown" | "silent" | "weak" | "healthy" | "hot"
export type AudioTranscriptSegment = { start_ms: number; end_ms: number; text: string }
export type AudioTranscriptionDetail = { text: string; segments: AudioTranscriptSegment[] }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
export type CodeLanguage = "rust" | "python" | "java_script" | "type_script" | "go" | "java" | "c_sharp" | "cpp" | "html" | "css" | "shell" | "json" | "toml" | "yaml" | "markdown"
export type ConfidenceWord = { text: string; confidence: number }
/**
 * A suggested dictionary entry derived from a user correction.
 */
export type CorrectionSuggestion = { 
/**
 * The original (wrong) word or phrase.
 */
from: string; 
/**
 * The corrected word or phrase.
 */
to: string; 
/**
 * How many times this exact correction has been recorded (including this one, if `record` was called).
 */
count: number; 
/**
 * True if `from` is already in the dictionary.
 */
already_in_dict: boolean; 
/**
 * True if the count has reached the auto-add threshold.
 */
auto_add: boolean }
export type CustomSounds = { start: boolean; stop: boolean }
export type DictionaryEntry = { from: string; to: string }
export type EngineType = "Parakeet"
export type GpuKind = "none" | "integrated" | "dedicated" | "unknown"
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_action_key: number | null; model_name: string | null; confidence_payload: TranscriptionConfidencePayload | null }
export type HistoryStats = { total_entries: number; total_words: number; entries_today: number; entries_this_week: number; most_used_model: string | null }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
export type IntegritySnapshot = { release_build: boolean; binary_sha256: string | null; tamper_flags: string[]; executable_path: string | null }
export type KeyboardImplementation = "tauri" | "native_keyboard"
export type LLMPrompt = { id: string; name: string; prompt: string }
/**
 * Aggregated stats about what Vocalype has learned from user corrections.
 */
export type LearningStats = { 
/**
 * Total number of correction events recorded (may include repeated pairs).
 */
total_corrections_recorded: number; 
/**
 * Number of distinct (from, to) pairs seen at least once.
 */
distinct_corrections: number; 
/**
 * Total entries in the user dictionary (manual + auto-learned).
 */
dictionary_entries: number; 
/**
 * Pairs that have reached the auto-add threshold (≥ AUTO_ADD_THRESHOLD).
 */
auto_learned_pairs: number; 
/**
 * Top 5 most-corrected pairs, sorted by count descending.
 */
top_corrections: TopCorrection[] }
export type LicenseRuntimeState = { state: LicenseState; reason: string | null; device_id: string | null; grant_expires_at: string | null; offline_expires_at: string | null; grace_until: string | null; entitlement_status: string | null; last_refreshed_at: string | null; integrity_anomalies: string[] }
export type LicenseState = "online_valid" | "offline_valid" | "expired"
export type LifecycleStateEvent = { state: TranscriptionLifecycleState; operation_id: number | null; binding_id: string | null; detail: string | null; recoverable: boolean; timestamp_ms: number }
export type LlamaServerStatus = { binary_ready: boolean; model_ready: boolean; server_running: boolean; port: number }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
export type MachineScoreDetails = { ram_score?: number; cpu_threads_score?: number; cpu_family_score?: number; gpu_prebench_bonus?: number; npu_prebench_bonus?: number; low_power_penalty?: number; power_penalty?: number; thermal_penalty?: number; final_score?: number; tier_reason?: string }
export type MachineTier = "low" | "medium" | "high"
export type MeetingEntry = { id: number; title: string; app_name: string; transcript: string; category: string; is_pinned: boolean; is_archived: boolean; summary: string; action_items: string; segments: MeetingSegmentEntry[]; created_at: number; updated_at: number }
export type MeetingSegmentEntry = { id: number; meeting_id: number; timestamp_ms: number; content: string; speaker: string }
export type MicrophonePermissionState = "unknown" | "granted" | "denied"
export type ModelInfo = { id: string; name: string; description: string; filename: string; url: string | null; expected_etag: string | null; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; is_custom: boolean; requires_license_key: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "min_30" | "hour_1" | "sec_5"
export type NoteEntry = { id: number; title: string; content: string; category: string; is_pinned: boolean; is_archived: boolean; summary: string; action_items: string; created_at: number; updated_at: number }
export type NpuKind = "none" | "qualcomm" | "intel" | "amd" | "unknown"
export type OllamaModelInfo = { name: string; size_gb: number }
export type OllamaStatus = { available: boolean; models: OllamaModelInfo[] }
export type OverlayPosition = "none" | "top" | "bottom"
export type ParakeetDiagnosticsSnapshot = { active_session: ParakeetSessionDiagnostics | null; recent_sessions: ParakeetSessionDiagnostics[] }
export type ParakeetFailureMode = "healthy" | "underchunking_long_utterance" | "overtrim_overlap" | "missing_word_timestamps" | "retry_recovered_chunk" | "final_chunk_hallucination" | "low_audio_density" | "boundary_word_loss"
export type ParakeetSessionDiagnostics = { session_id: number; operation_id: number | null; binding_id: string; model_id: string; model_name: string | null; provider: string; selected_language: string; device_name: string | null; recording_mode: string; chunk_interval_samples: number; chunk_overlap_samples: number; total_chunks: number; empty_chunks: number; retry_chunks: number; filtered_chunks: number; trimmed_words_total: number; chunks_without_word_timestamps: number; chunk_candidates_rejected: number; chunk_candidates_sent: number; output_words: number; finalization_recoveries: number; duration_secs: number; audio_to_word_ratio: number; estimated_issue: ParakeetFailureMode; quality_risk_score: number; assembled_preview: string; last_updated_ms: number }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type PipelineProfileEvent = { binding_id: string; created_at_ms: number; path: string; model_id: string | null; model_name: string | null; audio_duration_ms: number | null; transcription_chars: number; total_duration_ms: number; completed: boolean; error_code: string | null; steps: PipelineStepTiming[] }
export type PipelineStepTiming = { step: string; duration_ms: number; started_at_ms: number; finished_at_ms: number; detail: string | null }
export type PostProcessAction = { key: number; name: string; description?: string | null; prompt: string; model?: string | null; provider_id?: string | null }
export type PostProcessProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; models_endpoint?: string | null; supports_structured_output?: boolean }
export type PowerMode = "normal" | "saver" | "unknown"
/**
 * Entry in the "recently detected apps" list (last N dictation sessions).
 */
export type RecentAppEntry = { process_name: string; window_title: string | null; category: AppContextCategory; detected_at_ms: number }
/**
 * How the user starts and stops a recording session.
 * 
 * Replaces the two booleans `push_to_talk` and `always_on_microphone` that
 * previously co-existed and could produce an ambiguous combined state.
 * 
 * ## Migration (T11)
 * - Old `push_to_talk = true`         → `RecordingMode::PushToTalk`
 * - Old `always_on_microphone = true`  → `RecordingMode::AlwaysOn`
 * - Both `false`                       → `RecordingMode::Toggle`
 */
export type RecordingMode = 
/**
 * Press shortcut once to start, press again to stop.
 */
"toggle" | 
/**
 * Hold shortcut to record, release to stop (default).
 */
"push_to_talk" | 
/**
 * Microphone is always listening; VAD decides when a utterance starts/ends.
 */
"always_on"
export type RecordingRetentionPeriod = 
/**
 * Kept for deserialization compatibility with older settings files.
 * Treated as `Months3` at runtime — "never delete indefinitely" is not
 * a GDPR-compliant default.
 */
"preserve_limit" | "days_3" | "weeks_2" | "months_3"
export type RuntimeDiagnostics = { captured_at_ms: number; app_version: string; lifecycle_state: TranscriptionLifecycleState; last_lifecycle_event: LifecycleStateEvent; recent_errors: RuntimeErrorEvent[]; selected_model: string; loaded_model_id: string | null; loaded_model_name: string | null; model_loaded: boolean; paste_method: string; clipboard_handling: string; selected_language: string; selected_microphone: string | null; selected_output_device: string | null; is_recording: boolean; is_paused: boolean; microphone_stream_open: boolean; microphone_backend_ready: boolean; selected_microphone_available: boolean; microphone_permission_state: MicrophonePermissionState; input_level_state: AudioInputLevelState; input_energy_ema: number; input_peak_energy: number; adaptive_silence_threshold_ms: number | null; operation_id: number | null; active_stage: TranscriptionLifecycleState | null; last_audio_error: string | null; partial_result: boolean; device_resolution: string | null; cancelled_at_stage: TranscriptionLifecycleState | null; current_app_context: AppTranscriptionContext | null; last_transcription_app_context: AppTranscriptionContext | null; adaptive_voice_profile_enabled: boolean; adaptive_voice_profile: VoiceProfile | null; active_voice_profile_segment: VoiceProfileSegment | null; active_voice_runtime_adjustment: VoiceRuntimeAdjustment | null; recent_pipeline_profiles: PipelineProfileEvent[]; parakeet_diagnostics: ParakeetDiagnosticsSnapshot; adaptive_machine_profile: AdaptiveMachineProfile | null }
export type RuntimeErrorEvent = { code: string; stage: RuntimeErrorStage; message: string; recoverable: boolean; operation_id: number | null; device_name: string | null; model_id: string | null; timestamp_ms: number }
export type RuntimeErrorStage = "capture" | "vad" | "transcription" | "post_process" | "paste" | "shortcut" | "model" | "system" | "unknown"
export type SavedProcessingModel = { id: string; provider_id: string; model_id: string; label: string }
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SoundTheme = "marimba" | "pop" | "custom"
export type StartupWarmupPhase = "idle" | "preparing" | "ready" | "failed"
export type StartupWarmupReason = "no_model_selected" | "model_not_downloaded" | "preparing_microphone" | "preparing_model" | "ready" | "microphone_error" | "model_error"
export type StartupWarmupStatus = { phase: StartupWarmupPhase; reason: StartupWarmupReason; can_record: boolean; microphone_checked: boolean; microphone_ready: boolean; model_ready: boolean; blocking_reason: string | null; message: string; detail: string | null; updated_at_ms: number }
/**
 * A single entry in the top-corrections list.
 */
export type TopCorrection = { from: string; to: string; count: number }
export type TranscriptionConfidencePayload = { engine: string; overall_confidence: number; mapping_stable: boolean; words: ConfidenceWord[] }
export type TranscriptionLifecycleState = "idle" | "preparing_microphone" | "recording" | "paused" | "stopping" | "transcribing" | "processing" | "pasting" | "completed" | "cancelled" | "error"
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"
/**
 * The user's learned vocabulary profile.
 */
export type UserProfile = { 
/**
 * Words the model knows to look for (custom_words in settings).
 */
learned_terms: string[]; 
/**
 * How many of those were synced automatically from the dictionary.
 */
auto_synced_count: number }
export type VoiceFeedbackEntry = { id: string; created_at_ms: number; expected_text: string; actual_text: string; notes: string | null; selected_language: string | null; tags: string[]; keep_audio_reference: boolean; runtime: RuntimeDiagnostics }
export type VoiceFeedbackInput = { expected_text: string; actual_text: string; notes?: string | null; selected_language?: string | null; tags?: string[]; keep_audio_reference?: boolean }
export type VoiceFeedbackSummary = { total_entries: number; top_languages: ([string, number])[]; top_tags: ([string, number])[]; top_input_levels: ([string, number])[]; top_issues: ([string, number])[] }
export type VoiceProfile = { sessions_count?: number; avg_words_per_minute?: number; avg_pause_ms?: number; preferred_terms?: string[]; last_updated_ms?: number | null; segments?: Partial<{ [key in string]: VoiceProfileSegment }> }
export type VoiceProfileSegment = { sessions_count?: number; avg_words_per_minute?: number; avg_pause_ms?: number; preferred_terms?: string[]; last_updated_ms?: number | null }
export type VoiceRuntimeAdjustment = { adjusted_chunk_seconds: number; adjusted_overlap_ms: number; vad_hangover_frames_delta: number; reason: string | null }
/**
 * A voice snippet: if the entire transcription matches `trigger` (case-insensitive,
 * trimmed), it is replaced by `expansion` before being pasted.
 */
export type VoiceSnippet = { id: string; trigger: string; expansion: string }
/**
 * A single actionable insight derived from the weekly data.
 */
export type WeeklyInsight = { 
/**
 * Machine-readable category: "peak_time" | "growth" | "decline" |
 * "learning" | "habit" | "milestone"
 */
kind: string; 
/**
 * Human-readable message body (in French, localized in the Rust layer
 * so the frontend just renders it).
 */
message: string; 
/**
 * Optional numeric value powering the message (e.g. "+23%", "9h").
 */
value: number | null }
/**
 * Full weekly report returned to the frontend.
 */
export type WeeklyReport = { period_start_ts: number; period_end_ts: number; sessions_this_week: number; sessions_last_week: number; words_this_week: number; words_last_week: number; avg_words_per_session: number; daily_sessions: number[]; peak_hour_label: string | null; corrections_total: number; profile_terms: number; dictionary_entries: number; insights: WeeklyInsight[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
